language: "Croatian"
translation_mapping:
  "personality": "ličnost"
  "the personality of God": "ličnost Boga"
  "quality or state being a person": "kvaliteta ili stanje koja nekog čine osobom"
  "the quality or state of God being a person": "kvaliteta ili stanje koja Boga čine osobom"
  "the express image of His person": "savršena slika Njegove osobe"
  "fundamental principles": "fundamentalni principi"
  "foundation principles": "temeljni principi"
  "fundamental beliefs": "temeljna vjerovanja"
  "pillars of our faith": "stupovi naše vjere"
  "waymarks": "međaši"
  "sentiments": "sentimenti"
  "Ellen White": "Ellen White"
  "Seventh-day Adventist Church": "Crkva Adventista Sedmoga Dana"
  "The Living Temple (the book)": "Živi Hram (knjiga)"
  "spiritualism": "spiritualizam"
  "spiritualizers": "spiritualisti"
  "the spiritual view": "duhovni pogled"
  "controversy": "kontroverza"
  "Testimonies for the Church Containing Letters to Physicians and Ministers Instruction to Seventh-Day Adventists": "Svjedočanstva za Zajednicu Koja Sadrže Pisma Upute Liječnicima i Propovjednicima Adventistima Sedmog Dana"
  "the Trinity doctrine": "doktrina o Trojstvu"
  "patchwork theories": "teorije krpanja"
  "A Declaration of the Fundamental Principles, Taught and Practiced by the Seventh-Day Adventists": "Deklaracija Fundamentalnih Principa koje Uče i Prakticiraju Adventisti Sedmog Dana"
  "trinitarian": "trinitarijanski"
bible_verse_translation: "Varaždinska Biblija HBN"