language: "Polish"
translation_mapping:
  "the personality of God": "osobowość Boga"
  "Ellen White": "Ellen White"
  "personality": "osobowość"
  "sentiments": "poglądy"
  "fundamental principles": "fundamentalne zasady"
  "foundation principles": "podstawowe zasady"
  "fundamental beliefs": "fundamentalne wierzenia"
  "The Living Temple (the book)": "The Living Temple"
  "waymarks": "znaki"
  "pillars of our faith": "filary naszej wiary"
  "quality or state being a person": "właściwość lub stan jako osoby"
  "the quality or state of God being a person": "właściwość lub stan Boga jako osoby"
  "spiritualizers": "spirytualiści"
  "spiritualism": "spirytualizm"
  "the spiritual view": "duchowy pogląd"
  "the express image of His person": "wyraz Jego istoty"
  "controversy": "spór"
  "Seventh-day Adventist Church": "Kościół Adwentystów Dnia Siódmego"
  "Testimonies for the Church Containing Letters to Physicians and Ministers Instruction to Seventh-Day Adventists": "Testimonies for the Church Containing Letters to Physicians and Ministers Instruction to Seventh-Day Adventists"
  "the Trinity doctrine": "doktryna o Trójcy"
  "patchwork theories": "Łatane teorie"
  "A Declaration of the Fundamental Principles, Taught and Practiced by the Seventh-Day Adventists": "Oświadczenie o fundamentalnych zasadach nauczanych i wyznawanych przez Adwentystów Dnia Siódmego"
bible_verse_translation: "Biblia UBG"


