language: "Polish"
translation_mapping:
  "the personality of God": "osobowość Boga"
  "Ellen White": "Ellen White"
  "personality": "osobowość "
  "sentiments": "poglądy "
  "fundamental principles": "fundamentalne zasady"
  "foundation principles": "podstawowe zasady"
  "fundamental beliefs": "fundamentalne wierzenia"
  "The Living Temple (the book)": "Żywa Świątynia (knjiga)"
  "spiritualizers": "spirytyści"
  "spiritualism": "spirytualizm"
  "express image of His person": "wyraźny obraz jego osoby"
  "waymarks": "znaki"
  "pillars": "filary"
  "pillars of our faith": "filary naszej wiary"
bible_verse_translation: "Biblia Warszawska"