language: "English"
translation_mapping:
  "personality": ""
  "the personality of God": ""
  "quality or state being a person": ""
  "the quality or state of God being a person": ""
  "the express image of His person": ""
  "fundamental principles": ""
  "foundation principles": ""
  "fundamental beliefs": ""
  "pillars of our faith": ""
  "waymarks": ""
  "sentiments": ""
  "Ellen White": ""
  "Seventh-day Adventist Church": ""
  "The Living Temple (the book)": ""
  "spiritualism": ""
  "spiritualizers": ""
  "the spiritual view": ""
  "controversy": ""
  "Testimonies for the Church Containing Letters to Physicians and Ministers Instruction to Seventh-Day Adventists": ""
  "the Trinity doctrine": ""
  "patchwork theories": ""
  "A Declaration of the Fundamental Principles, Taught and Practiced by the Seventh-Day Adventists": ""
  "trinitarian": ""
  "schorlars": ""
bible_verse_translation: "KJV - King James Version"