language: "French"
translation_mapping:
  "personality": "personnalité"
  "the personality of God": "la personnalité de Dieu"
  "quality or state being a person": "La qualité ou l'état par lequel quelqu'un est défini comme une personne"
  "the quality or state of God being a person": "la qualité ou l'état de Dieu comme étant une personne"
  "the express image of His person": "l'empreinte de sa personne"
  "fundamental principles": "les principes fondamentaux"
  "foundation principles": "les principes fondamentaux"
  "fundamental beliefs": "les croyances fondamentales"
  "pillars of our faith": "les piliers de notre foi"
  "waymarks": "repères"
  "sentiments": "raisonnement"
  "Ellen White": "Ellen White"
  "Seventh-day Adventist Church": "L'Église Adventiste du Septième Jour"
  "The Living Temple (the book)": "Le Temple Vivant (le livre)"
  "spiritualism": "spiritualisme"
  "spiritualizers": "spiritualistes"
  "the spiritual view": "la vue spiritualiste"
  "controversy": "controverse"
  "Testimonies for the Church Containing Letters to Physicians and Ministers Instruction to Seventh-Day Adventists": "Témoignages pour l'Église contenant des lettres aux médecins et aux pasteurs - Instruction aux Adventistes du Septième Jour"
  "the Trinity doctrine": "la doctrine de la Trinité"
  "patchwork theories": "théories de rapiècement"
  "A Declaration of the Fundamental Principles, Taught and Practiced by the Seventh-Day Adventists": "Déclaration des Principes Fondamentaux Enseignés et Pratiqués par les Adventistes du Septième Jour"
  "scholars": "érudits"
  "only begotten Son": "seul Fils engendré"
bible_verse_translation: "Ostervald 2018"