language: "Spanish"
translation_mapping:
  "personality": "personalidad"
  "the personality of God": "la personalidad de Dios"
  "quality or state being a person": "cualidad o estado de ser una persona"
  "the quality or state of God being a person": "la cualidad o estado de Dios siendo una persona"
  "the express image of His person": "la imagen misma de su sustancia"
  "fundamental principles": "Principios Fundamentales"
  "foundation principles": "principios fundacionales"
  "fundamental beliefs": "creencias fundamentales"
  "pillars of our faith": "pilares de nuestra fe"
  "waymarks": "hitos"
  "sentiments": "sentimientos"
  "Ellen White": "Elena G. de White"
  "Seventh-day Adventist Church": "Iglesia Adventista del Séptimo Día"
  "The Living Temple (the book)": "The Living Temple"
  "spiritualism": "espiritualismo"
  "spiritualizers": "espiritualizadores"
  "the spiritual view": "la vista espiritual"
  "controversy": "controversia"
  "Testimonies for the Church Containing Letters to Physicians and Ministers Instruction to Seventh-Day Adventists": "Testimonies for the Church Containing Letters to Physicians and Ministers Instruction to Seventh-Day Adventists"
  "the Trinity doctrine": "la doctrina trinitaria"
  "patchwork theories": "teorías de parches"
  "A Declaration of the Fundamental Principles, Taught and Practiced by the Seventh-Day Adventists": "Declaración de los Principios Fundamentales, Enseñados y Practicados por los Adventistas del Séptimo Día"
  "schorlars": "académicos"
bible_verse_translation: ""