language: "Swahili"
translation_mapping:
  "personality": "Umbile"
  "the personality of God": "Umbile la Mungu"
  "quality or state being a person": "Ubora au hali ya kuwa Nafsi"
  "the quality or state of God being a person": "Ubora au hali ya Mungu kuwa Nafsi"
  "the express image of His person": "Chapa kamili ya Umbile Wake"
  "fundamental principles": "Kanuni za Kimsingi"
  "foundation principles": "Kanuni za Msingi"
  "fundamental beliefs": "Mafundisho za Kimsingi"
  "pillars of our faith": "Nguzo za Imani yetu"
  "waymarks": "Viashiria njia"
  "sentiments": "Maoni"
  "Ellen White": "Ellen White"
  "Seventh-day Adventist Church": "Waadventista Wasabato"
  "The Living Temple (the book)": "The Living Temple"
  # "spiritualism": ""
  # "spiritualizers": ""
  # "the spiritual view": ""
  "controversy": "Mgogoro"
  "Testimonies for the Church Containing Letters to Physicians and Ministers Instruction to Seventh-Day Adventists": "Testimonies for the Church containing Letters to Physicians and Ministers Instruction to Seventh-Day Adventist"
  "the Trinity doctrine": "Fundisho la Utatu"
  "patchwork theories": "Nadharia za Kiraka"
  "A Declaration of the Fundamental Principles, Taught and Practiced by the Seventh-Day Adventists": "A Declaration of the Fundamental Principles ,Taught and Practiced by the Seventh- Day Adventists"
  "schorlars": "Wasomi"
bible_verse_translation: "KJV - King James Version"